---
title       : One-Hit Wonder Application
subtitle    : 
author      : Mike
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## One Hit Wonder Application

<h3> The One-Hit Wonder Application is as easy as 1, 2, 3! </h3>

--- .class #id 

## Step 1: Find your time range

<p> Use the top slider to select the time period you care about.  You can choose a range including as early as 1940 and as recent as 2015. </p>

<p> The application will only consider songs by each artist during the selected time period, so if your favorite artist had 7 big hits spanning 1972 to 1978, but you select a time range of 1960 to 1972, only the hits in 1972 will be used to determine how big of a "One Hit Wonder" your favorite artist is.</p>


---

## Step 2: Weight the Importance of that "Big Hit"

<p> To be a one hit wonder, your notoriety really depends on that one big hit, right?  Use the second slider to weight how important it is the artist's fame/infamy depends on a single hit.</p>

<p> The more heavily you weight this factor, the more you'll see artists at the top of the list that only have one song in their arsenal.</p>


---
## Step 3: Weight the Importance of Overall Musical Fame

<p> There are a ton of artists who only had one hit, but we can't even remember their names because even with their one 'hit', they're just too obscure.</p>  
<p>Use the third and final slider to weight the overall fame into the calculation and see names you really recognize rise to the top of the list!</p>

---
## Have fun!
<p> And thanks for playing :) </p>



